name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker_test:
    name: Docker Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker-compose build
    - name: Run Tests in Docker (local config)
      run: |
        docker-compose run inferno bin/run_tests.sh
        docker-compose down
    - name: Run Tests in Docker (server config)
      run: |
        docker-compose -f docker-compose.postgres.yml run inferno bin/run_tests.sh
        docker-compose -f docker-compose.postgres.yml down
